### ISSUE TITLE
Making Roles Multi-Tenant RoleCheckEditor.getTreeItems()

### ISSUE THREAD

**Issue by vsudik** [volkanceylan/MultiTenancy#2]
RoleCheckEditor.getTreeItems() return list of all roles from all tenants then I am trying to set role for user, but  I expect to see list of roles  only from current tenant.
I use Administration.RoleService.List service call to fix it, maybe, You can insert a better solution into MultiTenancy.

        protected getTreeItems() {
            Administration.RoleService.List({}, response => { this.RoleList = response.Entities.map(x => x);}
                , { async: false });

            return this.RoleList.map(role => <Serenity.CheckTreeItem<any>>{
                id: role.RoleId.toString(),
                text: role.RoleName
            });

**Comment by volkanceylan** [comment]
Thanks, but there is already explanation on how you should do it in guide

**Comment by vsudik** [comment]
Thanks, I found very smart declarative solution by IMultiTenantRow interface for roles in grid in guide, but did not found solution for roles in RoleCheckEditor, I will try to read and understand guide one more.
